language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --no-deps
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    secure: "jJlDJn+CJ0RDOzUY0cKDOmHEzEQZFUcKiCJcEp3ECMnX94iB0tfgckDnYzXRWBzl9H/9a8S8/fwCqtx7EmXqIuLWr0piW1nu2aLp6Yn8XlKd//6cYMF+by5w2UO3LuM488YOC4t3AjgkxV2qwV7FPR95VKdKGD3efyOSl73pbxI="



notifications:
  email:
    on_success: never
